name: QuickKart API Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore BlinkDemoApi.sln

      - run: dotnet build BlinkDemoApi.sln -c Release


      - run: dotnet publish BlinkDemoApi.sln -c Release -o publish

      - uses: actions/upload-artifact@v4
        with:
          name: quickkart-publish
          path: publish
